import '@/features/popup/popup'
import '@/layout/header/header.js'
import '@/layout/menu/menu.js'
import '@/layout/cookie-notification/cookie-notification.js'

import '@/components/main-hero/main-hero.js'
import '@/components/our-clients/our-clients.js'
import '@/components/our-projects/our-projects.js'
import '@/components/seo/seo.js'
import '@/components/specialists/specialists.js'
